name: "Runner setup"
description: "Sets up the runner with basic prerequisites"
runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "DOTNET_VERSION=10.0.x" >> $GITHUB_ENV
        echo "DOTNET_NOLOGO=false" >> $GITHUB_ENV
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=true" >> $GITHUB_ENV
        echo "NUKE_TELEMETRY_OPTOUT=true" >> $GITHUB_ENV

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore .NET tools
      shell: bash
      run: dotnet tool restore
